debug: true
server:
  port: 8888

spring:
  datasource:
    username: sa
    password:
    url: jdbc:h2:mem:batch;MODE=PostgreSQL;DB_CLOSE_DELAY=-1;
  h2:
    console:
      enabled: true
      path: /h2
  batch:
    job:
      enabled: false
    jdbc:
      initialize-schema: embedded

logging:
  level:
    org.hibernate.type: TRACE